# .goreleaser.yaml
version: 2
project_name: waxseal

before:
  hooks:
    - go mod tidy

builds:
  - id: waxseal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/waxseal
    ldflags:
      - -s -w -X github.com/shermanhuman/waxseal/internal/cli.Version={{.Version}} -X github.com/shermanhuman/waxseal/internal/cli.Commit={{.Commit}} -X github.com/shermanhuman/waxseal/internal/cli.BuildDate={{.Date}}

archives:
  - id: nix
    builds: [waxseal]
    formats: [tar.gz]
    goos: [linux, darwin]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: windows
    builds: [waxseal]
    formats: [zip]
    goos: [windows]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
