package cli2

import (
	"context"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	"github.com/shermanhuman/waxseal/internal/ops"
	"github.com/shermanhuman/waxseal/internal/ui"
)

// ── secret retire ──────────────────────────────────────────────────────────

func newSecretRetireCmd(app *App) *cobra.Command {
	var reason, replacedBy string
	var deleteManifest bool
	var cmd *cobra.Command
	cmd = &cobra.Command{
		Use:   "retire [secret]",
		Short: "Mark a secret retired; optionally delete its manifest",
		Long: `Mark a secret retired. Retired secrets are skipped by reseal, rotate and
checks. Secret Manager entries are left untouched. Pass --delete-manifest
once nothing consumes the secret any more.`,
		Args:              argsUsage(cobra.MaximumNArgs(1)),
		ValidArgsFunction: app.completeSecret,
		RunE: app.run(Needs{Config: true, Metadata: true}, func(ctx context.Context, io *IO, args []string) (ui.Result, error) {
			svc, err := app.Service(ctx, Needs{}, false)
			if err != nil {
				return nil, err
			}
			name, err := app.secretArg(io, svc, args, 0)
			if err != nil {
				return nil, err
			}
			if deleteManifest && !app.Flags.DryRun {
				if err := io.In.Confirm("delete the manifest of " + name); err != nil {
					return nil, err
				}
			}
			res, err := svc.Retire(ops.RetireInput{ShortName: name, Reason: reason, ReplacedBy: replacedBy, DeleteManifest: deleteManifest, DryRun: app.Flags.DryRun})
			if err != nil {
				return nil, err
			}
			summary := name + " retired"
			var next []string
			if len(res.Changes) == 0 {
				summary = name + " is already retired"
			} else if !deleteManifest {
				next = []string{"once nothing uses it: waxseal secret retire " + name + " --delete-manifest"}
			}
			return mutation(app, res, summary, append(next, commitNext(res)...)...), nil
		}),
	}
	cmd.Flags().StringVar(&reason, "reason", "", "why the secret is retired")
	cmd.Flags().StringVar(&replacedBy, "replaced-by", "", "short name of the secret that replaces it")
	cmd.Flags().BoolVar(&deleteManifest, "delete-manifest", false, "also delete the SealedSecret manifest")
	return cmd
}

// ── rotate ─────────────────────────────────────────────────────────────────

type rotateResult struct {
	*mutationResult
	Rotated []string `json:"rotated"`
	Skipped []string `json:"skipped,omitempty"`
}

func (r *rotateResult) Text(p *ui.Printer) {
	r.mutationResult.Text(p)
	for _, k := range r.Skipped {
		p.Info("skipped %s: not generated by waxseal; set a new value with `waxseal key set`", k)
	}
}

func newRotateCmd(app *App) *cobra.Command {
	var cmd *cobra.Command
	cmd = &cobra.Command{
		Use:   "rotate [secret] [key]...",
		Short: "Generate new values for generated keys and reseal them",
		Long: `Generate a new value for each generated key, store it as a new Secret
Manager version and re-encrypt the manifest. With no keys named, every
generated key of the secret is rotated and the others are listed as
skipped. Keys rotated elsewhere get their new value with ` + "`waxseal key set`" + `.`,
		GroupID:           groupOps,
		Args:              argsUsage(cobra.ArbitraryArgs),
		ValidArgsFunction: app.completeSecretKey,
		RunE: app.run(needsMutate, func(ctx context.Context, io *IO, args []string) (ui.Result, error) {
			svc, err := app.Service(ctx, needsMutate, false)
			if err != nil {
				return nil, err
			}
			name, err := app.secretArg(io, svc, args, 0)
			if err != nil {
				return nil, err
			}
			keys := args[min(1, len(args)):]
			if !app.Flags.DryRun {
				what := "all generated keys of " + name
				if len(keys) > 0 {
					what = strings.Join(keys, ", ") + " in " + name
				}
				if err := io.In.Confirm("rotate " + what); err != nil {
					return nil, err
				}
			}
			res, err := svc.Rotate(ctx, ops.RotateInput{ShortName: name, Keys: keys, DryRun: app.Flags.DryRun})
			if err != nil {
				return nil, err
			}
			summary := fmt.Sprintf("rotated %d key(s) in %s", len(res.Rotated), name)
			if len(res.Rotated) == 0 {
				summary = "nothing to rotate in " + name
			}
			return &rotateResult{mutationResult: mutation(app, res.MutationResult, summary, commitNext(res.MutationResult)...), Rotated: res.Rotated, Skipped: res.Skipped}, nil
		}),
	}
	return cmd
}

// ── reseal ─────────────────────────────────────────────────────────────────

type resealResult struct {
	Cert    *ops.CertStatus    `json:"cert,omitempty"`
	Secrets []ops.ResealResult `json:"secrets"`
	DryRun  bool               `json:"dryRun"`
	Failed  int                `json:"failed"`
}

func (r *resealResult) Text(p *ui.Printer) {
	if r.Cert != nil && r.Cert.Updated {
		p.Success("certificate updated (fingerprint %s)", r.Cert.ClusterFingerprint[:16])
	}
	verb := "resealed"
	if r.DryRun {
		verb = "would reseal"
	}
	for _, s := range r.Secrets {
		if s.Error != "" {
			p.Error("%s: %s", s.ShortName, s.Error)
			continue
		}
		p.Printf("%s %s (%d keys)\n", verb, s.ShortName, s.Keys)
	}
	if r.Failed > 0 {
		p.Warn("%d of %d secrets failed", r.Failed, len(r.Secrets))
	}
}

func newResealCmd(app *App) *cobra.Command {
	var skipCertCheck bool
	var cmd *cobra.Command
	cmd = &cobra.Command{
		Use:   "reseal [secret]...",
		Short: "Re-encrypt manifests from Secret Manager",
		Long: `Fetch every key's value from Secret Manager and re-encrypt the manifest.
With no secrets named, every active secret is resealed.

Before sealing, the controller's current certificate is compared with the
one in the repo; a rotated certificate is stored (after confirmation) so
the new ciphertext matches the cluster. --skip-cert-check uses the repo
certificate as is, for CI without cluster access.

Exit 1 when any secret failed.`,
		GroupID:           groupOps,
		Args:              argsUsage(cobra.ArbitraryArgs),
		ValidArgsFunction: app.completeSecret,
		RunE: app.run(Needs{Config: true, Metadata: true, GSM: true, Kubeseal: true}, func(ctx context.Context, io *IO, args []string) (ui.Result, error) {
			svc, err := app.Service(ctx, Needs{GSM: true}, false)
			if err != nil {
				return nil, err
			}
			out := &resealResult{DryRun: app.Flags.DryRun}
			if !skipCertCheck {
				st, err := app.refreshCert(ctx, io, svc, "the certificate changed; update it and reseal with the new one")
				if err != nil {
					return nil, err
				}
				out.Cert = st
			}
			svc.Sealer, err = app.Sealer()
			if err != nil {
				return nil, err
			}
			err = io.P.Spin(ctx, "Resealing", func(progress func(string)) error {
				var err error
				out.Secrets, err = svc.Reseal(ctx, ops.ResealInput{ShortNames: args, DryRun: app.Flags.DryRun, Progress: progress})
				return err
			})
			if err != nil {
				return nil, err
			}
			for _, s := range out.Secrets {
				if s.Error != "" {
					out.Failed++
				}
			}
			if out.Failed > 0 {
				return out, &ExitError{Code: ExitFailure}
			}
			return out, nil
		}),
	}
	cmd.Flags().BoolVar(&skipCertCheck, "skip-cert-check", false, "do not compare the repo certificate with the controller's")
	return cmd
}

// refreshCert compares certificates and, when they differ, asks before
// storing the controller's. A cluster that cannot be reached is a
// warning, not an error: the repo certificate is used.
func (a *App) refreshCert(ctx context.Context, io *IO, svc *ops.Service, why string) (*ops.CertStatus, error) {
	var st *ops.CertStatus
	err := io.P.Spin(ctx, "Checking the controller certificate", func(func(string)) error {
		var err error
		st, err = svc.RefreshCert(ctx, false)
		return err
	})
	if err != nil {
		io.P.Warn("could not fetch the controller certificate (%v); using the repo certificate", err)
		return nil, nil
	}
	if !st.Changed {
		return st, nil
	}
	io.P.Warn("controller certificate differs from the repo certificate (%s vs %s)", st.ClusterFingerprint[:16], short(st.RepoFingerprint))
	if a.Flags.DryRun {
		return st, nil
	}
	if err := io.In.Confirm(why); err != nil {
		return nil, err
	}
	return svc.RefreshCert(ctx, true)
}

func short(fp string) string {
	if fp == "" {
		return "none"
	}
	return fp[:16]
}

// ── cert fetch ─────────────────────────────────────────────────────────────

type certResult struct{ *ops.CertStatus }

func (r *certResult) Text(p *ui.Printer) {
	switch {
	case r.Updated:
		p.Success("certificate stored (fingerprint %s)", r.ClusterFingerprint[:16])
		p.Next([]string{"re-encrypt every secret with it: waxseal reseal"})
	case r.Changed:
		p.Warn("certificate differs (repo %s, cluster %s); not written", short(r.RepoFingerprint), r.ClusterFingerprint[:16])
	default:
		p.Success("certificate is up to date (fingerprint %s)", r.ClusterFingerprint[:16])
	}
}

func newCertCmd(app *App) *cobra.Command {
	var cmd *cobra.Command
	cmd = &cobra.Command{Use: "cert", Short: "Manage the controller certificate", GroupID: groupSetup}
	cmd.AddCommand(&cobra.Command{
		Use:   "fetch",
		Short: "Fetch the controller's sealing certificate into the repo",
		Args:  argsUsage(cobra.NoArgs),
		RunE: app.run(Needs{Config: true, Kubeseal: true}, func(ctx context.Context, io *IO, _ []string) (ui.Result, error) {
			svc, err := app.Service(ctx, Needs{}, false)
			if err != nil {
				return nil, err
			}
			st, err := svc.RefreshCert(ctx, !app.Flags.DryRun)
			if err != nil {
				return nil, err
			}
			return &certResult{st}, nil
		}),
	})
	return cmd
}

// ── init ───────────────────────────────────────────────────────────────────

func newInitCmd(app *App) *cobra.Command {
	var project, controllerNS, controllerName string
	var force bool
	var cmd *cobra.Command
	cmd = &cobra.Command{
		Use:   "init",
		Short: "Write .waxseal/config.yaml for this repository",
		Long: `Create the waxseal configuration: the GCP project that holds the secrets
and where the sealed-secrets controller runs. Nothing else is touched;
fetch the certificate with ` + "`waxseal cert fetch`" + ` and register
manifests with ` + "`waxseal import`" + `.`,
		GroupID: groupSetup,
		Args:    argsUsage(cobra.NoArgs),
		RunE: app.run(Needs{}, func(ctx context.Context, io *IO, _ []string) (ui.Result, error) {
			svc, err := app.Service(ctx, Needs{}, false)
			if err != nil {
				return nil, err
			}
			project, err := io.In.String(ui.Spec{Flag: "--project", Title: "GCP project ID", Help: "the project whose Secret Manager holds the values"},
				cmd.Flags().Changed("project"), project, "", nonEmpty)
			if err != nil {
				return nil, err
			}
			ns, err := io.In.String(ui.Spec{Flag: "--controller-namespace", Title: "Controller namespace"}, cmd.Flags().Changed("controller-namespace"), controllerNS, "kube-system", nonEmpty)
			if err != nil {
				return nil, err
			}
			name, err := io.In.String(ui.Spec{Flag: "--controller-name", Title: "Controller service name"}, cmd.Flags().Changed("controller-name"), controllerName, "sealed-secrets", nonEmpty)
			if err != nil {
				return nil, err
			}
			res, err := svc.Init(ops.InitInput{ProjectID: project, ControllerNamespace: ns, ControllerName: name, Force: force, DryRun: app.Flags.DryRun})
			if err != nil {
				return nil, err
			}
			return mutation(app, res, "initialised for project "+project,
				"fetch the controller certificate: waxseal cert fetch",
				"find existing manifests: waxseal discover"), nil
		}),
	}
	cmd.Flags().StringVar(&project, "project", "", "GCP project ID")
	cmd.Flags().StringVar(&controllerNS, "controller-namespace", "kube-system", "namespace of the sealed-secrets controller")
	cmd.Flags().StringVar(&controllerName, "controller-name", "sealed-secrets", "service name of the sealed-secrets controller")
	cmd.Flags().BoolVar(&force, "force", false, "overwrite an existing config")
	return cmd
}

// ── import ─────────────────────────────────────────────────────────────────

type importResult struct {
	Secrets []importOne `json:"secrets"`
	DryRun  bool        `json:"dryRun"`
}

type importOne struct {
	ShortName string `json:"shortName"`
	*ops.ImportResult
	Error string `json:"error,omitempty"`
}

func (r *importResult) Text(p *ui.Printer) {
	if len(r.Secrets) == 0 {
		p.Info("Every manifest is registered; name a secret to re-import it.")
		return
	}
	for _, s := range r.Secrets {
		if s.Error != "" {
			p.Error("%s: %s", s.ShortName, s.Error)
			continue
		}
		verb := "imported"
		if r.DryRun {
			verb = "would import"
		}
		p.Printf("%s %s: %d added, %d updated", verb, s.ShortName, len(s.Added), len(s.Updated))
		if len(s.Templated) > 0 {
			p.Printf(", templated: %s", strings.Join(s.Templated, " "))
		}
		p.Println()
		if len(s.MissingInCluster) > 0 {
			p.Warn("%s: in metadata but not in the cluster: %s", s.ShortName, strings.Join(s.MissingInCluster, ", "))
		}
	}
	if !r.DryRun {
		p.Next([]string{"review rotation modes: waxseal secret show <secret>; adjust with waxseal key edit", "commit .waxseal/metadata and the manifests"})
	}
}

func newImportCmd(app *App) *cobra.Command {
	var cmd *cobra.Command
	cmd = &cobra.Command{
		Use:   "import [secret]...",
		Short: "Register manifests by reading their values from the cluster",
		Long: `Read each secret's plaintext from the cluster, store it in Secret Manager
and write metadata for it. Names are the ones ` + "`waxseal discover`" + ` suggests,
or registered secrets to re-import. Connection strings become computed
keys with the password as their {{secret}}. Every key is registered as
externally rotated; change that with ` + "`waxseal key edit`" + `.`,
		GroupID: groupSetup,
		Args:    argsUsage(cobra.ArbitraryArgs),
		RunE: app.run(Needs{Config: true, GSM: true, Kubeseal: true, Kubectl: true}, func(ctx context.Context, io *IO, args []string) (ui.Result, error) {
			svc, err := app.Service(ctx, Needs{GSM: true, Kubeseal: true, Kubectl: true}, false)
			if err != nil {
				return nil, err
			}
			names := args
			if len(names) == 0 {
				found, err := svc.Discover()
				if err != nil {
					return nil, err
				}
				for _, d := range found {
					if d.Registered == "" {
						names = append(names, d.Suggested)
					}
				}
				if len(names) == 0 {
					return &importResult{DryRun: app.Flags.DryRun}, nil
				}
				if err := io.In.Confirm("import " + strings.Join(names, ", ")); err != nil {
					return nil, err
				}
			}
			out := &importResult{DryRun: app.Flags.DryRun}
			failed := 0
			err = io.P.Spin(ctx, "Importing", func(progress func(string)) error {
				for _, name := range names {
					progress(name)
					one := importOne{ShortName: name}
					res, err := svc.Import(ctx, ops.ImportInput{ShortName: name, DryRun: app.Flags.DryRun})
					if err != nil {
						one.Error = err.Error()
						failed++
					} else {
						one.ImportResult = res
					}
					out.Secrets = append(out.Secrets, one)
				}
				return nil
			})
			if err != nil {
				return nil, err
			}
			if failed > 0 {
				return out, &ExitError{Code: ExitFailure}
			}
			return out, nil
		}),
	}
	return cmd
}
