package cli

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/shermanhuman/waxseal/internal/files"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize waxseal in a GitOps repository",
	Long: `Initialize waxseal configuration in the current repository.

This command creates:
  - .waxseal/config.yaml - Main configuration file
  - .waxseal/metadata/   - Directory for secret metadata
  - keys/pub-cert.pem    - Placeholder for controller certificate

Interactive mode prompts for:
  - GCP Project ID for Secret Manager
  - Controller namespace and name

Use --non-interactive with required flags for CI/automation.`,
	RunE: runInit,
}

var (
	initNonInteractive bool
	initProjectID      string
	initControllerNS   string
	initControllerName string
)

func init() {
	rootCmd.AddCommand(initCmd)
	initCmd.Flags().BoolVar(&initNonInteractive, "non-interactive", false, "Run without prompts")
	initCmd.Flags().StringVar(&initProjectID, "project-id", "", "GCP Project ID for Secret Manager")
	initCmd.Flags().StringVar(&initControllerNS, "controller-namespace", "kube-system", "Sealed Secrets controller namespace")
	initCmd.Flags().StringVar(&initControllerName, "controller-name", "sealed-secrets", "Sealed Secrets controller service name")
}

func runInit(cmd *cobra.Command, args []string) error {
	waxsealDir := filepath.Join(repoPath, ".waxseal")
	metadataDir := filepath.Join(waxsealDir, "metadata")
	keysDir := filepath.Join(repoPath, "keys")
	configFile := filepath.Join(waxsealDir, "config.yaml")

	// Check if already initialized
	if _, err := os.Stat(configFile); err == nil && !yes {
		fmt.Printf("waxseal already initialized at %s\n", waxsealDir)
		fmt.Print("Overwrite? [y/N]: ")
		if !confirmOverwrite() {
			fmt.Println("Aborted.")
			return nil
		}
	}

	// Get project ID
	projectID := initProjectID
	if projectID == "" && !initNonInteractive {
		projectID = prompt("GCP Project ID for Secret Manager: ")
		if projectID == "" {
			return fmt.Errorf("project ID is required")
		}
	}
	if projectID == "" && initNonInteractive {
		return fmt.Errorf("--project-id is required in non-interactive mode")
	}

	controllerNS := initControllerNS
	controllerName := initControllerName

	// Interactive prompts for controller
	if !initNonInteractive {
		if input := prompt(fmt.Sprintf("Controller namespace [%s]: ", controllerNS)); input != "" {
			controllerNS = input
		}
		if input := prompt(fmt.Sprintf("Controller service name [%s]: ", controllerName)); input != "" {
			controllerName = input
		}
	}

	// Create directories
	if err := os.MkdirAll(metadataDir, 0o755); err != nil {
		return fmt.Errorf("create metadata directory: %w", err)
	}
	if err := os.MkdirAll(keysDir, 0o755); err != nil {
		return fmt.Errorf("create keys directory: %w", err)
	}

	// Generate config
	config := generateConfig(projectID, controllerNS, controllerName)

	if dryRun {
		fmt.Println("Would create config:")
		fmt.Println(config)
		return nil
	}

	// Write config atomically
	writer := files.NewAtomicWriter()
	if err := writer.Write(configFile, []byte(config)); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	// Create .gitkeep in metadata
	gitkeepPath := filepath.Join(metadataDir, ".gitkeep")
	if err := os.WriteFile(gitkeepPath, []byte{}, 0o644); err != nil {
		return fmt.Errorf("write .gitkeep: %w", err)
	}

	// Create placeholder cert file
	certPath := filepath.Join(keysDir, "pub-cert.pem")
	if _, err := os.Stat(certPath); os.IsNotExist(err) {
		placeholder := `# Sealed Secrets Controller Public Certificate
#
# Fetch from your cluster:
#   kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system \
#     --fetch-cert > keys/pub-cert.pem
#
# Or from the controller pod:
#   kubectl -n kube-system get secret sealed-secrets-key -o jsonpath='{.data.tls\.crt}' | base64 -d
#
# This file should be committed to Git.
`
		if err := os.WriteFile(certPath, []byte(placeholder), 0o644); err != nil {
			return fmt.Errorf("write cert placeholder: %w", err)
		}
	}

	fmt.Printf("✓ Created %s\n", configFile)
	fmt.Printf("✓ Created %s\n", metadataDir)
	fmt.Printf("✓ Created %s (placeholder)\n", certPath)

	fmt.Println("\nNext steps:")
	fmt.Println("  1. Fetch your Sealed Secrets controller certificate:")
	fmt.Printf("     kubeseal --controller-name=%s --controller-namespace=%s --fetch-cert > %s\n",
		controllerName, controllerNS, filepath.Join("keys", "pub-cert.pem"))
	fmt.Println("  2. Run 'waxseal discover' to find existing SealedSecrets")
	fmt.Println("  3. Or manually create metadata files in .waxseal/metadata/")

	return nil
}

func generateConfig(projectID, controllerNS, controllerName string) string {
	return fmt.Sprintf(`# waxseal configuration
# Generated by waxseal init

version: "1"

store:
  kind: gsm
  projectId: %s
  # defaultReplication: automatic

controller:
  namespace: %s
  serviceName: %s

cert:
  repoCertPath: keys/pub-cert.pem
  verifyAgainstCluster: true

discovery:
  includeGlobs:
    - "apps/**/*.yaml"
    - "**/*sealed*.yaml"
  excludeGlobs:
    - "**/kustomization.yaml"
    - "**/*.tmpl.yaml"

# reminders:
#   enabled: false
#   provider: google-calendar
#   calendarId: primary
#   leadTimeDays: [30, 7, 1]
#   auth:
#     kind: adc
`, projectID, controllerNS, controllerName)
}

func prompt(message string) string {
	fmt.Print(message)
	reader := bufio.NewReader(os.Stdin)
	input, _ := reader.ReadString('\n')
	return strings.TrimSpace(input)
}

func confirmOverwrite() bool {
	reader := bufio.NewReader(os.Stdin)
	input, _ := reader.ReadString('\n')
	input = strings.TrimSpace(strings.ToLower(input))
	return input == "y" || input == "yes"
}
