package cli

import (
	"context"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	"github.com/shermanhuman/waxseal/internal/ops"
	"github.com/shermanhuman/waxseal/internal/ui"
)

// ── secret retire ──────────────────────────────────────────────────────────

func newSecretRetireCmd(app *App) *cobra.Command {
	var reason, replacedBy string
	var deleteManifest bool
	cmd := &cobra.Command{
		Use:   "retire [secret]",
		Short: "Mark a secret retired; optionally delete its manifest",
		Long: `Mark a secret retired. Retired secrets are skipped by reseal, rotate and
checks. Secret Manager entries are left untouched. Pass --delete-manifest
once nothing consumes the secret any more.`,
		Args:              argsUsage(cobra.MaximumNArgs(1)),
		ValidArgsFunction: app.completeSecret,
	}
	cmd.RunE = app.run(Needs{Config: true, Metadata: true}, func(ctx context.Context, io *IO, args []string) (ui.Result, error) {
		svc, err := app.Service(ctx, Needs{}, false)
		if err != nil {
			return nil, err
		}
		name, err := app.secretArg(io, svc, args, 0)
		if err != nil {
			return nil, err
		}
		if deleteManifest && !app.Flags.DryRun {
			if err := io.In.Confirm("delete the manifest of " + name); err != nil {
				return nil, err
			}
		}
		res, err := svc.Retire(ops.RetireInput{ShortName: name, Reason: reason, ReplacedBy: replacedBy, DeleteManifest: deleteManifest, DryRun: app.Flags.DryRun})
		if err != nil {
			return nil, err
		}
		summary := name + " retired"
		var next []string
		if len(res.Changes) == 0 {
			summary = name + " is already retired"
		} else if !deleteManifest {
			next = []string{"once nothing uses it: waxseal secret retire " + name + " --delete-manifest"}
		}
		return mutation(app, res, summary, append(next, commitNext(res)...)...), nil
	})
	cmd.Flags().StringVar(&reason, "reason", "", "why the secret is retired")
	cmd.Flags().StringVar(&replacedBy, "replaced-by", "", "short name of the secret that replaces it")
	cmd.Flags().BoolVar(&deleteManifest, "delete-manifest", false, "also delete the SealedSecret manifest")
	return cmd
}

// ── rotate ─────────────────────────────────────────────────────────────────

type rotateResult struct {
	*mutationResult
	Rotated []string `json:"rotated"`
	Skipped []string `json:"skipped,omitempty"`
}

func (r *rotateResult) Text(p *ui.Printer) {
	r.mutationResult.Text(p)
	for _, k := range r.Skipped {
		p.Info("skipped %s: not generated by waxseal; set a new value with `waxseal key set`", k)
	}
}

func newRotateCmd(app *App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "rotate [secret] [key]...",
		Short: "Generate new values for generated keys and reseal them",
		Long: `Generate a new value for each generated key, store it as a new Secret
Manager version and re-encrypt the manifest. With no keys named, every
generated key of the secret is rotated and the others are listed as
skipped. Keys rotated elsewhere get their new value with ` + "`waxseal key set`" + `.`,
		GroupID:           groupOps,
		Args:              argsUsage(cobra.ArbitraryArgs),
		ValidArgsFunction: app.completeSecretKey,
	}
	cmd.RunE = app.run(needsMutate(), func(ctx context.Context, io *IO, args []string) (ui.Result, error) {
		svc, err := app.Service(ctx, needsMutate(), false)
		if err != nil {
			return nil, err
		}
		name, err := app.secretArg(io, svc, args, 0)
		if err != nil {
			return nil, err
		}
		keys := args[min(1, len(args)):]
		if !app.Flags.DryRun {
			what := "all generated keys of " + name
			if len(keys) > 0 {
				what = strings.Join(keys, ", ") + " in " + name
			}
			if err := io.In.Confirm("rotate " + what); err != nil {
				return nil, err
			}
		}
		res, err := svc.Rotate(ctx, ops.RotateInput{ShortName: name, Keys: keys, DryRun: app.Flags.DryRun})
		if err != nil {
			return nil, err
		}
		summary := fmt.Sprintf("rotated %d key(s) in %s", len(res.Rotated), name)
		if len(res.Rotated) == 0 {
			summary = "nothing to rotate in " + name
		}
		return &rotateResult{mutationResult: mutation(app, res.MutationResult, summary, commitNext(res.MutationResult)...), Rotated: res.Rotated, Skipped: res.Skipped}, nil
	})
	return cmd
}

// ── reseal ─────────────────────────────────────────────────────────────────

type resealResult struct {
	Cert    *ops.CertStatus    `json:"cert,omitempty"`
	Secrets []ops.ResealResult `json:"secrets"`
	DryRun  bool               `json:"dryRun"`
	Failed  int                `json:"failed"`
}

func (r *resealResult) Text(p *ui.Printer) {
	if r.Cert != nil && r.Cert.Updated {
		p.Success("certificate updated (fingerprint %s)", r.Cert.ClusterFingerprint[:16])
	}
	verb := "resealed"
	if r.DryRun {
		verb = "would reseal"
	}
	for _, s := range r.Secrets {
		if s.Error != "" {
			p.Error("%s: %s", s.ShortName, s.Error)
			continue
		}
		p.Printf("%s %s (%d keys)\n", verb, s.ShortName, s.Keys)
	}
	if r.Failed > 0 {
		p.Warn("%d of %d secrets failed", r.Failed, len(r.Secrets))
	}
}

func newResealCmd(app *App) *cobra.Command {
	var skipCertCheck bool
	cmd := &cobra.Command{
		Use:   "reseal [secret]...",
		Short: "Re-encrypt manifests from Secret Manager",
		Long: `Fetch every key's value from Secret Manager and re-encrypt the manifest.
With no secrets named, every active secret is resealed.

Before sealing, the controller's current certificate is compared with the
one in the repo; a rotated certificate is stored (after confirmation) so
the new ciphertext matches the cluster. --skip-cert-check uses the repo
certificate as is, for CI without cluster access.

Exit 1 when any secret failed.`,
		GroupID:           groupOps,
		Args:              argsUsage(cobra.ArbitraryArgs),
		ValidArgsFunction: app.completeSecret,
	}
	cmd.RunE = app.run(Needs{Config: true, Metadata: true, GSM: true, Kubeseal: true}, func(ctx context.Context, io *IO, args []string) (ui.Result, error) {
		svc, err := app.Service(ctx, Needs{GSM: true}, false)
		if err != nil {
			return nil, err
		}
		out := &resealResult{DryRun: app.Flags.DryRun}
		if !skipCertCheck {
			st, err := app.refreshCert(ctx, io, svc, "the certificate changed; update it and reseal with the new one")
			if err != nil {
				return nil, err
			}
			out.Cert = st
		}
		svc.Sealer, err = app.Sealer()
		if err != nil {
			return nil, err
		}
		err = io.P.Spin(ctx, "Resealing", func(progress func(string)) error {
			var err error
			out.Secrets, err = svc.Reseal(ctx, ops.ResealInput{ShortNames: args, DryRun: app.Flags.DryRun, Progress: progress})
			return err
		})
		if err != nil {
			return nil, err
		}
		for _, s := range out.Secrets {
			if s.Error != "" {
				out.Failed++
			}
		}
		if out.Failed > 0 {
			return out, &ExitError{Code: ExitFailure}
		}
		return out, nil
	})
	cmd.Flags().BoolVar(&skipCertCheck, "skip-cert-check", false, "do not compare the repo certificate with the controller's")
	return cmd
}

// refreshCert compares certificates and, when they differ, asks before
// storing the controller's. A cluster that cannot be reached is a
// warning, not an error: the repo certificate is used.
func (a *App) refreshCert(ctx context.Context, io *IO, svc *ops.Service, why string) (*ops.CertStatus, error) {
	var st *ops.CertStatus
	err := io.P.Spin(ctx, "Checking the controller certificate", func(func(string)) error {
		var err error
		st, err = svc.RefreshCert(ctx, false)
		return err
	})
	if err != nil {
		io.P.Warn("could not fetch the controller certificate (%v); using the repo certificate", err)
		return nil, nil
	}
	if !st.Changed {
		return st, nil
	}
	io.P.Warn("controller certificate differs from the repo certificate (%s vs %s)", st.ClusterFingerprint[:16], short(st.RepoFingerprint))
	if a.Flags.DryRun {
		return st, nil
	}
	if err := io.In.Confirm(why); err != nil {
		return nil, err
	}
	return svc.RefreshCert(ctx, true)
}

func short(fp string) string {
	if fp == "" {
		return "none"
	}
	return fp[:16]
}
