package ops

import (
	"context"
	"errors"
	"fmt"

	"github.com/shermanhuman/waxseal/internal/core"
)

// ErrNotGenerated is wrapped when rotate is asked to rotate a key whose
// value waxseal cannot generate.
var ErrNotGenerated = errors.New("key is not generated by waxseal; set its value with `key set`")

// RotateInput selects keys to rotate. With no Keys, every generated key of
// the secret is rotated and the others are reported as skipped.
type RotateInput struct {
	ShortName string
	Keys      []string
	DryRun    bool
}

// RotateResult reports what was rotated.
type RotateResult struct {
	*MutationResult
	Rotated []string `json:"rotated"`
	Skipped []string `json:"skipped,omitempty"` // non-generated keys, when none were named
}

// Rotate generates new values for generated keys, stores them in GSM and
// re-seals them. A named key that is not generated is an error.
func (s *Service) Rotate(ctx context.Context, in RotateInput) (*RotateResult, error) {
	m, err := s.activeMetadata(in.ShortName)
	if err != nil {
		return nil, err
	}
	var targets []*core.KeyMetadata
	res := &RotateResult{}
	if len(in.Keys) == 0 {
		for i := range m.Keys {
			k := &m.Keys[i]
			if isGenerated(k) {
				targets = append(targets, k)
			} else {
				res.Skipped = append(res.Skipped, k.KeyName)
			}
		}
	} else {
		for _, name := range in.Keys {
			k := m.Key(name)
			if k == nil {
				return nil, fmt.Errorf("%s/%s: %w", m.ShortName, name, ErrKeyNotFound)
			}
			if !isGenerated(k) {
				return nil, fmt.Errorf("%s/%s: %w", m.ShortName, name, ErrNotGenerated)
			}
			targets = append(targets, k)
		}
	}
	if len(targets) == 0 {
		res.MutationResult = &MutationResult{ShortName: m.ShortName, DryRun: in.DryRun}
		return res, nil
	}

	writes := make([]keyWrite, 0, len(targets))
	for _, k := range targets {
		value, err := core.GenerateValue(k.Rotation.Generator)
		if err != nil {
			return nil, fmt.Errorf("generate %s/%s: %w", m.ShortName, k.KeyName, err)
		}
		w, err := s.valueWrite(ctx, k, value)
		if err != nil {
			return nil, err
		}
		writes = append(writes, w)
		res.Rotated = append(res.Rotated, k.KeyName)
	}
	res.MutationResult, err = s.apply(ctx, m, writes, false, in.DryRun)
	if err != nil {
		return nil, err
	}
	return res, nil
}

func isGenerated(k *core.KeyMetadata) bool {
	return k.Rotation != nil && k.Rotation.Mode == core.RotationGenerated && k.Rotation.Generator != nil && k.ActiveRef() != nil
}
